package com.orginsight.service;

import com.orginsight.dto.response.AiInsightResponse;

/**
 * AI insights service. When gemini.api-key / gemini.enabled are configured,
 * insights are generated by Google Gemini from an aggregated, PII-free
 * summary of the organization's live data. If AI is not configured or a
 * call fails, this transparently falls back to a static/derived heuristic
 * so the AI Insights screen always returns a usable response.
 */
public interface AiInsightsService {
    AiInsightResponse getInsights();
}
