package com.orginsight.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.orginsight.dto.request.AskAiRequest;
import com.orginsight.dto.response.AiInsightResponse;
import com.orginsight.dto.response.AskAiResponse;
import com.orginsight.service.AiCopilotService;
import com.orginsight.service.AiInsightsService;

import jakarta.validation.Valid;

/**
 * Serves AI-generated (Google Gemini) or, when AI is unavailable,
 * static/derived insights. See AiInsightsService for details.
 */
@RestController
@RequestMapping("/api/ai")
public class AiInsightsController {

    private static final Logger logger = LoggerFactory.getLogger(AiInsightsController.class);

    private final AiInsightsService aiInsightsService;
    private final AiCopilotService aiCopilotService;

    public AiInsightsController(AiInsightsService aiInsightsService, AiCopilotService aiCopilotService) {
        this.aiInsightsService = aiInsightsService;
        this.aiCopilotService = aiCopilotService;
    }

    @GetMapping("/insights")
    public ResponseEntity<AiInsightResponse> getInsights() {
        logger.info("[controller] GET /api/ai/insights received");
        AiInsightResponse response = aiInsightsService.getInsights();
        logger.info("[controller] GET /api/ai/insights returning (aiGenerated={})",
                response.getNote() != null && response.getNote().startsWith("Generated by Google Gemini"));
        return ResponseEntity.ok(response);
    }

    @PostMapping("/ask")
    public ResponseEntity<AskAiResponse> ask(@Valid @RequestBody AskAiRequest request) {
        logger.info("[controller] POST /api/ai/ask received - one HTTP request in, one service call out");
        AskAiResponse response = aiCopilotService.ask(request.getQuestion());
        logger.info("[controller] POST /api/ai/ask returning (aiGenerated={}, errorType={})",
                response.isAiGenerated(), response.getErrorType());
        return ResponseEntity.ok(response);
    }
}
